pipeline:
  name: bad-js
  identifier: badjs
  projectIdentifier: demoproj
  orgIdentifier: default
  tags: {}
  properties:
    ci:
      codebase:
        connectorRef: account.RNGit
        repoName: bad-js-app
        build: <+input>
  stages:
    - stage:
        name: Build
        identifier: Build
        description: ""
        type: CI
        spec:
          cloneCodebase: true
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Docker
            spec: {}
          execution:
            steps:
              - parallel:
                  - step:
                      type: Semgrep
                      name: Semgrep_custom_ruleset
                      identifier: Semgrep_1
                      spec:
                        mode: orchestration
                        config: default
                        target:
                          type: repository
                          workspace: ./
                          detection: auto
                        advanced:
                          log:
                            level: info
                          fail_on_severity: high
                          args:
                            cli: "--config ./semgrep/config.yaml"
                        settings:
                          SEMGREP_BRANCH: <+codebase.sourceBranch>
                          SEMGREP_PR_ID: <+codebase.prNumber>
                          SEMGREP_REPO_URL: <+codebase.repoUrl>
                          SEMGREP_REPO_NAME: rnelson01/bad-js-app
                          SEMGREP_COMMIT: <+codebase.commitRef>
                        auth:
                          access_token: <+secrets.getValue("account.semgrep_app")>
                      when:
                        stageStatus: Success
                  - step:
                      type: Semgrep
                      spec:
                        mode: orchestration
                        config: default
                        target:
                          type: repository
                          workspace: ./
                          detection: auto
                        advanced:
                          log:
                            level: debug
                          fail_on_severity: high
                        settings:
                          SEMGREP_BRANCH: <+codebase.sourceBranch>
                          SEMGREP_PR_ID: <+codebase.prNumber>
                          SEMGREP_REPO_URL: <+codebase.repoUrl>
                          SEMGREP_COMMIT: <+codebase.commitSha>
                          SEMGREP_REPO_NAME: rnelson01/bad-js-app
                        auth:
                          access_token: <+secrets.getValue("account.semgrep_app")>
                      name: semgrep oss
                      identifier: semgrep_oss
