rules:
  - id: docs-react-dangerouslysetinnerhtml
    languages:
      - typescript
      - javascript
    message: >
      Setting HTML from code is risky because it’s easy to inadvertently expose
      your users to a cross-site scripting (XSS) attack.
    pattern-either:
      - pattern: |
          <$X dangerouslySetInnerHTML=... />
      - pattern: |
          {dangerouslySetInnerHTML: ...}
    severity: WARNING
  - id: docs-react-dangerouslysetinnerhtml
    patterns:
      - pattern-either:
          - pattern: |
              <$X dangerouslySetInnerHTML=... />
          - pattern: |
              {dangerouslySetInnerHTML: ...}
    message: >
      Setting HTML from code is risky because it’s easy to inadvertently expose
      your users to a cross-site scripting (XSS) attack.
    severity: WARNING
    languages:
      - js
  - id: find-unverified-transactions
    patterns:
      - pattern: |
          public $RETURN $METHOD(...){
              ...
              make_transaction($T);
              ...
          }
      - pattern-not: |
          public $RETURN $METHOD(...){
              ...
              verify_transaction(...);
              ...
              make_transaction(...);
              ...
          }
    message: >
      In $METHOD, there's a call to make_transaction() without first calling
      verify_transaction() on the Transaction object.
    severity: WARNING
    languages:
      - java
  - id: cve-2024-4142
    patterns:
      - pattern: |
          jfrog rt
    languages:
      - yaml
    message: >
      Jfrog cli api-tokens are deprecated, please use curl.
    severity: WARNING
